language: node_js
node_js:
- stable
branches:
  only:
  - master
deploy:
  edge: true
  skip_cleanup: true
  provider: npm
  email: at@webhouse.dk
  api_key:
    secure: gQ3mh+1d0vuo4Tog9lr3GAGcdbtRM0kmA6FtX3pOleC4bX487nRzl9OPGP6j93+F5rDS3kbva1PXo2/CMwOly04qdQ7s7s4l0G67/1B3O4yRXbKJDEjh5F8i2I14nQ5fw1+CPPkgsF5s1EQRZXQUBjkoVmYOyEgq54BvZnwfYVbX5yf4EzucrM7t9jKZPh3fMe8TYT1P+vvQEt5X8j/SjaTauHpPsX7kHDu4var4/ZqyFvVIIkgabvcIpS1mSRAF/JHhgtek7V8EqbIGUQNnZQweCOlJGEFw0GyVweTKmi9FyYpbNOKYj5xD6iXPjllu2Iq9GAhhMQzTP69Eb9qmZZpxNx/H/yL3Msb2WbJEA8AVXiIUaoVy2jzCJZIkEingEP8PArVLUq09Fwo+ieUti1+igWM+S/djUQUYPkOSMGgwMRJnWzwjwhq474Flv0c5qAL/mN1ufK0fWL8OHCWF4jjyXwToH/8Zp3ObMQ2V78Ws93cfNsOXenCUqbcoMC/uxx1W1+XWtGg9y3xYW60dSftvPrc3ZG4DX1GXZInk4GuWsnlSe8AqreD6ouDB5vuWdFYGRyG3xTWdk3dohwlsIIymFbZp8+LZVMIPu5ebKVyDjZJeUW1OfOcS7tUtWgknTnjYhrVE2quXp7z2LYrIrh8I4V67sdg0RbUIKgYAu6w=
  on:
    repo: senti-iot/senti-game-model-water
notifications:
  email:
    recipients:
    - at@webhouse.dk
    on_success: never
    on_failure: always
  slack:
    secure: LEE9VlsZ6fc7jdv7gbLSrwLtOTOAEvyUUXiqxnNyV2/B/wBdWAF7AYcbSyQJXesD/eqGzFe5uT2RaaERAMN3GWMR0++0z4eDqSOb2B3OLfzQorgA663GWkepnbroSDXDzcNm+2JWsm7HsC/EBzvEQZYcAHQgd4AF1lLZpMdUwFXwt+gg9VKN6v3kc7HnJsi13CSZ5SH7lpL2wLoJBJO0/T8OjJRfMAdxxFLWjr9Rxd8uNRRva5g5I9UCVh/KiHrxCnugf3ysloVIf+hBa/FL54axDYcp8XaAwOzZuKor1/OTxPzG12gAuAgnZbQyYa3JvQUgNQKyFwkFesPC4ZfbdGi5WNiu7I6BJP8rir1kUlelRfwWM1iLDKCkTmP/ml8Ac7wdW45xTvj/PjeeSwJ/s6wpuiiDU/eAoahntL/U57kbjXdPIxNOsSzhdlO32+uwtwIUqQIbCocklvylclda9gmoxH+JQNSnZKt5kFjnCpja2sb/GRL7fHsO35mIblwT6LTu3DkVbMNXLVxlixmMcZu2tIPKshSYQH50gD7D+fymP4jopoxqIFFDrWIDlvm5Kbw4bOn8aha8KyE7y91Xet0U9cruowO1xGOboJDWDvF5B88+kK4weuI2ZfTCW28jotceLrF/qChm0yUElg84shOoGI3swrBFM3i0VpWDRJ4=
